# permissions for end users to edit yurtappsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yurtappset-editor-role
rules:
- apiGroups:
  - apps.openyurt.io
  resources:
  - yurtappsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - yurtappsets/status
  verbs:
  - get
